### PR TITLE
Fix typo, crio-o to cri-o

### PR DESCRIPTION
**Pull request by mjlshen**
Signed-off-by: Michael Shen <mishen@umich.edu>

### CODE REVIEW

**Comment by haircommander** [comment]
LGTM, thanks for the PR @mjlshen ! You'll need to sign off the git commit, by either doing `git commit --amend -s` via the cli, or adding something like `Signed-off-by: $NAME <$EMAIL>`

**Comment by mjlshen** [comment]
@haircommander Sorry, I'm kind of new at this, does that seem right?

**Comment by haircommander** [comment]
sorry, not quite.
are you working off of the git cli?

**Comment by mjlshen** [comment]
Yeah, I'm leaning towards just starting over and adding the sign-off to the commit since it's so small

**Comment by haircommander** [comment]
that'd work for me :)

**Pull request closed without merging**
