### PR TITLE
Add fresh coat of paint to the site

### PR DESCRIPTION
**Pull request by rhamilto**
@jwforres asked me to freshen up the look of the site.  This is my
initial attempt at doing so.  Feedback encouraged.  cc: @spadgett, @sg00dwin

127 0 0 1_4000_ ipad
127 0 0 1_4000_ iphone 6

### CODE REVIEW

**Comment by runcom** [comment]
:+1:

**Comment by jwforres** [comment]
thanks @rhamilto 

@runcom anything else yall would like to see while he's looking at this?

**Comment by rhatdan** [comment]
Should we reference buildah/libpod and skopeo from the site?

**Comment by aweiteka** [comment]
Looks great. I'd like to get this in now. Thanks.

**Comment by aweiteka** [comment]
> Should we reference buildah/libpod and skopeo from the site?

@rhatdan do we want to co-opt other tech like this? We risk another projectatomic catch-all site, IMHO.

**Comment by runcom** [comment]
I tend to agree with Aaron here, we may revisit that later after a longer discussion

**Comment by rhatdan** [comment]
Fine. Eventually we want to encourage the use of the package formerly known as kpod with CRI-O.  But lets merge this.

**Pull request merged**
