### PR TITLE
Make architecture easier to understand.

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@mrunalp @aweiteka PTAL

**Comment by rhatdan** [comment]
@mhausenblas PTAL

**Comment by mhausenblas** [comment]
LGTM @rhatdan (as usual, I'd uppercase Kubernetes but other than that … ;)

**Comment by mrunalp** [comment]
LGTM

**Pull request merged**
