### PR TITLE
update installation instructions

### PR DESCRIPTION
**Pull request by haircommander**
Signed-off-by: Peter Hunt <pehunt@redhat.com>
```release-note
none
```

### CODE REVIEW

**Comment by haircommander** [comment]
@umohnani8 @mrunalp @saschagrunert @rhatdan @TomSweeneyRedHat PTAL

**Comment by haircommander** [comment]
fixes https://github.com/cri-o/cri-o/issues/4214 https://github.com/cri-o/cri-o.io/issues/47

**Comment by TomSweeneyRedHat** [comment]
LGTM
and apologies for the very tardy review, I somehow missed the initial notification.

**Comment by umohnani8** [comment]
LGTM

**Comment by haircommander** [comment]
can someone /lgtm plz

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Pull request merged**
