### PR TITLE
update Ubuntu installation instruction

### PR DESCRIPTION
**Pull request by Slach**
Signed-off-by: Slach <bloodjazman@gmail.com>

close https://github.com/cri-o/cri-o.io/pull/42
I hope DCO exists

### CODE REVIEW

**Comment by haircommander** [comment]
you may need to rebase off of master again. the DCO failure is on a merge commit, which shouldn't be included in this PR (it's already merged)

**Comment by haircommander** [comment]
thanks for the PR @Slach BTW

**Comment by Slach** [comment]
@haircommander could you suggest me
which git commands should I use to rebase with master?
I tried `git pull --rebase upstream master`
but bot show me label "dco-commit:no" instead of apply rebase

**Comment by haircommander** [comment]
what I do is
```bash
git fetch upstream
git rebase upstream/master
git push -f origin ubuntu_install
```

**Comment by Slach** [comment]
@haircommander done, thanks for instruction

**Pull request merged**
