### PR TITLE
index.md: fixups for use it and repos

### PR DESCRIPTION
**Pull request by runcom**
Signed-off-by: Antonio Murdaca <runcom@redhat.com>

### CODE REVIEW

**Comment by runcom** [comment]
@rhatdan please merge this

**Comment by rhatdan** [comment]
@runcom I can't.  @aweiteka Please Merge.

**Comment by mhausenblas** [comment]
Looks great, congrats to the re-design! One thing, though: I don't manage to find a link to GitHub anymore, is this intentionally so?

**Comment by runcom** [comment]
We probably need to add that

**Comment by rhatdan** [comment]
Lets add a "Contribute" bullet and link the github and IRC there.

**Pull request merged**
